openapi: 3.0.0
info:
  title: Search API
  description: 'API for handling various search functionalities including keyword search, popular searches, and autocomplete.'
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /api/v1/search:
    get:
      summary: Search products
      description: 'Search for products based on different criteria like keywords, categories, brands, etc.'
      parameters:
        - description: Keyword to search for
          in: query
          name: keyword
          required: false
          schema:
            type: string
        - description: Category to filter products
          in: query
          name: category
          required: false
          schema:
            type: string
        - description: Brand to filter products
          in: query
          name: brand
          required: false
          schema:
            type: string
        - description: Minimum price range filter
          in: query
          name: min_price
          required: false
          schema:
            format: float
            type: number
        - description: Maximum price range filter
          in: query
          name: max_price
          required: false
          schema:
            format: float
            type: number
        - description: 'Field to sort by (e.g., price, popularity, rating)'
          in: query
          name: sort_by
          required: false
          schema:
            enum:
              - price
              - popularity
              - rating
            type: string
        - description: Sort order (asc or desc)
          in: query
          name: order
          required: false
          schema:
            enum:
              - asc
              - desc
            type: string
      responses:
        '200':
          description: Successful search results
          content:
            application/json:
              schema:
                properties:
                  facets:
                    properties:
                      brands:
                        items:
                          properties:
                            doc_count:
                              type: integer
                            key:
                              type: string
                          type: object
                        type: array
                      categories:
                        items:
                          properties:
                            doc_count:
                              type: integer
                            key:
                              type: string
                          type: object
                        type: array
                    type: object
                  results:
                    items:
                      properties:
                        brand:
                          type: string
                        category:
                          type: string
                        description:
                          type: string
                        name:
                          type: string
                        popularity:
                          type: integer
                        price:
                          format: float
                          type: number
                        product_id:
                          type: string
                        rating:
                          format: float
                          type: number
                      type: object
                    type: array
                type: object
        '400':
          description: Invalid input
        '404':
          description: No results found
        '500':
          description: Internal server error
  /api/v1/autocomplete:
    get:
      description: Get autocomplete suggestions based on partial input. It includes detecting misspelled words and providing suggestions for corrected spellings if needed.
      parameters:
        - description: The partial input for which to retrieve suggestions.
          in: query
          name: q
          schema:
            type: string
      responses:
        '200':
          description: Autocomplete suggestions
          content:
            application/json:
              schema:
                properties:
                  suggestions:
                    items:
                      type: string
                    type: array
                type: object
        '400':
          description: Invalid input
        '500':
          description: Server error
  /api/v1/popular-searches:
    get:
      description: 'Provides a list of commonly searched terms that appear as soon as the search field is activated. This helps users quickly find popular results, even before they start typing. It''s based on searches from all users, making it useful for first-time users to see what others are searching for'
      responses:
        '200':
          description: A list of popular searches
          content:
            application/json:
              schema:
                properties:
                  popularSearches:
                    items:
                      type: string
                    type: array
                type: object
        '500':
          description: Server error
