openapi: 3.0.3
info:
  title: Cart Calculation API
  description: API for calculating cart values including item-level savings and digital deal references.
  version: 1.0.0
servers:
  - url: 'https://api.example.com/v1'
paths:
  /cart/calculate:
    post:
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/TenantIdentifyHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      summary: Calculate cart values
      description: Pass the entire basket to the NCR promotional engine to return accurate cart-level calculations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromotionRequest'
      responses:
        '200':
          description: Successful response with cart calculations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromotionResponseBaseResponseObject'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    CarNumberInPath:
      in: path
      name: CardNumber
      description: 'The CardNumber. It is a loyalty card returned by a third-party provider, such as Clutch or Retalix.'
      required: true
      schema:
        type: string
    AuthorizationHeader:
      in: header
      name: Authorization
      required: true
      schema:
        type: string
        example: Bearer your-access-token
      description: 'Bearer token for authorization. Format: ''Bearer $accessToken'', where $accessToken is obtained from ''api/Token'' endpoint.'
    TenantIdentifyHeader:
      in: header
      name: TenantIdentify
      required: true
      schema:
        type: string
        example: MCT
      description: 'Tenant identifier, which must be ''MCT''.'
    ContentTypeHeader:
      in: header
      name: Content-Type
      required: true
      schema:
        type: string
        enum:
          - application/json
      description: Specifies the format of the payload being sent. Must be 'application/json' for this endpoint.
  schemas:
    BasketOffer:
      type: object
      properties:
        offerName:
          type: string
          nullable: true
        discountAmount:
          type: number
          format: double
      additionalProperties: false
    ItemOffer:
      type: object
      properties:
        offerName:
          type: string
          nullable: true
        gtin:
          type: string
          nullable: true
        discountAmount:
          type: number
          format: double
      additionalProperties: false
    Product:
      type: object
      properties:
        gtin:
          type: string
          nullable: true
        quantity:
          $ref: '#/components/schemas/Quantity'
        itemPrice:
          type: number
          format: double
        qualifies:
          $ref: '#/components/schemas/Qualify'
      additionalProperties: false
    PromotionRequest:
      type: object
      properties:
        loyaltyId:
          type: string
          nullable: true
        totals:
          $ref: '#/components/schemas/Totals'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
          nullable: true
      additionalProperties: false
    PromotionResponse:
      type: object
      properties:
        basketOffers:
          type: array
          items:
            $ref: '#/components/schemas/BasketOffer'
          nullable: true
        itemOffers:
          type: array
          items:
            $ref: '#/components/schemas/ItemOffer'
          nullable: true
      additionalProperties: false
    PromotionResponseBaseResponseObject:
      type: object
      properties:
        status:
          type: boolean
        errorMessage:
          type: string
          nullable: true
        errorCode:
          $ref: '#/components/schemas/ResponseErrorCode'
        correlationId:
          type: string
          format: uuid
        data:
          $ref: '#/components/schemas/PromotionResponse'
      additionalProperties: false
    Qualify:
      type: object
      properties:
        rewards:
          type: boolean
        discount:
          type: boolean
      additionalProperties: false
    Totals:
      type: object
      properties:
        itemsOnly:
          type: integer
          format: int32
        withoutTax:
          type: integer
          format: int32
        withTax:
          type: integer
          format: int32
      additionalProperties: false
    Quantity:
      type: object
      properties:
        unitType:
          type: string
          nullable: true
        units:
          type: number
          format: float
      additionalProperties: false
    ResponseErrorCode:
      enum:
        - 0
        - 1
        - 2
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 100
        - 101
        - 102
        - 103
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        - 400
        - 401
        - 402
        - 404
        - 405
        - 406
        - 407
        - 408
        - 409
        - 410
        - 411
        - 412
        - 413
        - 414
        - 415
        - 416
        - 417
        - 421
        - 422
        - 424
        - 426
        - 428
        - 429
        - 431
        - 451
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        - 506
        - 507
        - 508
        - 510
      type: integer
      format: int32
    ErrorDetails:
      type: object
      properties:
        Status:
          type: boolean
        Message:
          type: string
        ErrorCode:
          $ref: '#/components/schemas/ResponseErrorCode'
        Data:
          type: object
          items:
            type: string
        CorrelationId:
          type: string
          format: uuid
          description: Unique Identifier used for tracing and logging purposes.
  responses:
    BadRequest:
      description: Bad Request - The request was invalid or cannot be served. Check input format.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
    Unauthorized:
      description: Unauthorized - The request requires user authentication.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
    NotFound:
      description: Not Found - The server has not found anything matching the Request-URI.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
    InternalServerError:
      description: Internal Server Error - The server encountered an unexpected condition.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
